apiVersion: v1
kind: Service
metadata:
  name: shop-backend
  namespace: shop
spec:
  type: ClusterIP
  selector:
    app: shop-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP

